services:
  - type: worker
    name: telegram-ytdl-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7896182510:AAHprQJ36Yuc0gqYUJeiwfT_DIZ8QqK-FRo
    pythonVersion: 3.11.9
